# -*- coding: utf-8 -*-
"""лаб3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRxNHm1m-P1YjIUWTRCec78xFxb7jnP2

# Фильтрация ранговым методом
"""

import numpy as np
from PIL import Image

def rank_filter(image, filter_size, rank):
    width, height = image.size
    filter_half = filter_size // 2
    filtered_image = Image.new('L', (width, height))

    for x in range(width):
        for y in range(height):
            pixels = []
            for i in range(-filter_half, filter_half + 1):
                for j in range(-filter_half, filter_half + 1):
                    if 0 <= x + i < width and 0 <= y + j < height:
                        pixels.append(image.getpixel((x + i, y + j)))
            pixels.sort()
            filtered_image.putpixel((x, y), pixels[rank])

    return filtered_image

# Загрузка изображения
input_image = Image.open('/content/test_1.png').convert('L')

# Применение рангового фильтра
filtered_image = rank_filter(input_image, filter_size=6, rank=9)

# Сохранение результата
filtered_image.save('output_image_rank_filter.png')

res=Image.open("/content/output_image_rank_filter.png").convert('L')

res